services:
  spring:
    image: eclipse-temurin:21-jdk
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes: 
      - ./:/workspaces
    networks:
      - default
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=springboot
      - POSTGRES_USER=springuser
      - POSTGRES_PASSWORD=springpass
    networks:
      - default

networks:
  default: